apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-staging-datasource-provisioning
  namespace: staging
  labels:
    app: grafana-staging
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Google Cloud Monitoring
        type: stackdriver
        access: proxy
        isDefault: true
        jsonData:
          authenticationType: gce
          defaultProject: responsive-city-458413-a2
        editable: true

      - name: Google Managed Prometheus
        type: prometheus
        access: proxy
        url: https://monitoring.googleapis.com/v1/projects/responsive-city-458413-a2/location/global/prometheus
        isDefault: false
        jsonData:
          authenticationType: gce
          httpMethod: POST
        editable: true
