apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-provisioning
  namespace: production
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Google Cloud Monitoring
        type: stackdriver
        access: proxy
        isDefault: true
        jsonData:
          authenticationType: gce
          defaultProject: responsive-city-458413-a2
        editable: true
